Add credits client
holaplex/hub-core pull request #10
Opened 2023-04-27 02:36 UTC by ray-kast

- Added a TOML parser for the credits client.
- Add producer to credits client, minus schema.

2023-04-27 16:14 UTC, kespinola requested changes
I don't see api for reading the credit sheet. Did I miss or item to build?

2023-04-27 16:14 UTC, kespinola commented on crates/core/src/credits.rs
> +}
Need to send the user id of the initiator and the organization id when sending a deduction.

Also recommend calling it `send_deduction`

2023-04-27 20:09 UTC, kespinola commented on crates/core/src/credits.rs
> +}
`credits` isn't getting sent with the event. And maybe we have the caller pass the CreditEventKey { organization_id, user_id }

2023-04-28 14:02 UTC, imabdulbasit commented on crates/core/src/credits.rs
> +#[derive(Debug)]
```suggestion
#[derive(Debug, Clone)]
```
need the credits client to implement Clone

2023-04-28 14:03 UTC, imabdulbasit commented on crates/core/src/credits.rs
> +#[derive(Debug)]
```suggestion
#[derive(Debug, Clone)]
```
need the credits client to implement Clone

2023-05-02 06:23 UTC, imabdulbasit commented on crates/core/Cargo.toml
> +credits = ["kafka_internal", "strum", "toml"]
```suggestion
credits = ["kafka_internal", "strum", "toml", "rand"]
```

2023-05-02 17:25 UTC, imabdulbasit approved these changes

2023-05-02 18:24 UTC, merged